
// Code generated by 'go test'. DO NOT EDIT.

package main

import (
	"os"

	"testing"
	"testing/internal/testdeps"



	_test "github.com/imroc/req/v3"


)

var tests = []testing.InternalTest{

	{"TestRetryCancelledContext", _test.TestRetryCancelledContext},

	{"TestWrapRoundTrip", _test.TestWrapRoundTrip},

	{"TestAllowGetMethodPayload", _test.TestAllowGetMethodPayload},

	{"TestSetTLSHandshakeTimeout", _test.TestSetTLSHandshakeTimeout},

	{"TestSetDial", _test.TestSetDial},

	{"TestSetDialTLS", _test.TestSetDialTLS},

	{"TestSetFuncs", _test.TestSetFuncs},

	{"TestSetCookieJar", _test.TestSetCookieJar},

	{"TestTraceAll", _test.TestTraceAll},

	{"TestOnAfterResponse", _test.TestOnAfterResponse},

	{"TestOnBeforeRequest", _test.TestOnBeforeRequest},

	{"TestSetProxyURL", _test.TestSetProxyURL},

	{"TestSetProxy", _test.TestSetProxy},

	{"TestSetCommonContentType", _test.TestSetCommonContentType},

	{"TestSetCommonHeader", _test.TestSetCommonHeader},

	{"TestSetCommonHeaderNonCanonical", _test.TestSetCommonHeaderNonCanonical},

	{"TestSetCommonHeaders", _test.TestSetCommonHeaders},

	{"TestSetCommonHeadersNonCanonical", _test.TestSetCommonHeadersNonCanonical},

	{"TestSetCommonBasicAuth", _test.TestSetCommonBasicAuth},

	{"TestSetCommonBearerAuthToken", _test.TestSetCommonBearerAuthToken},

	{"TestSetUserAgent", _test.TestSetUserAgent},

	{"TestAutoDecode", _test.TestAutoDecode},

	{"TestSetTimeout", _test.TestSetTimeout},

	{"TestSetLogger", _test.TestSetLogger},

	{"TestSetScheme", _test.TestSetScheme},

	{"TestDebugLog", _test.TestDebugLog},

	{"TestSetCommonCookies", _test.TestSetCommonCookies},

	{"TestSetCommonQueryString", _test.TestSetCommonQueryString},

	{"TestSetCommonPathParams", _test.TestSetCommonPathParams},

	{"TestSetCommonPathParam", _test.TestSetCommonPathParam},

	{"TestAddCommonQueryParam", _test.TestAddCommonQueryParam},

	{"TestSetCommonQueryParam", _test.TestSetCommonQueryParam},

	{"TestSetCommonQueryParams", _test.TestSetCommonQueryParams},

	{"TestSetCommonQueryParamsFromValues", _test.TestSetCommonQueryParamsFromValues},

	{"TestSetCommonQueryParamsFromStruct", _test.TestSetCommonQueryParamsFromStruct},

	{"TestInsecureSkipVerify", _test.TestInsecureSkipVerify},

	{"TestSetTLSClientConfig", _test.TestSetTLSClientConfig},

	{"TestCompression", _test.TestCompression},

	{"TestKeepAlives", _test.TestKeepAlives},

	{"TestRedirect", _test.TestRedirect},

	{"TestGetTLSClientConfig", _test.TestGetTLSClientConfig},

	{"TestSetRootCertFromFile", _test.TestSetRootCertFromFile},

	{"TestSetRootCertFromString", _test.TestSetRootCertFromString},

	{"TestSetCerts", _test.TestSetCerts},

	{"TestSetCertFromFile", _test.TestSetCertFromFile},

	{"TestSetOutputDirectory", _test.TestSetOutputDirectory},

	{"TestSetBaseURL", _test.TestSetBaseURL},

	{"TestSetCommonFormDataFromValues", _test.TestSetCommonFormDataFromValues},

	{"TestSetCommonFormData", _test.TestSetCommonFormData},

	{"TestSetMultipartBoundaryFunc", _test.TestSetMultipartBoundaryFunc},

	{"TestFirefoxMultipartBoundaryFunc", _test.TestFirefoxMultipartBoundaryFunc},

	{"TestWebkitMultipartBoundaryFunc", _test.TestWebkitMultipartBoundaryFunc},

	{"TestClientClone", _test.TestClientClone},

	{"TestDisableAutoReadResponse", _test.TestDisableAutoReadResponse},

	{"TestEnableDumpAll", _test.TestEnableDumpAll},

	{"TestEnableDumpAllToFile", _test.TestEnableDumpAllToFile},

	{"TestEnableDumpAllAsync", _test.TestEnableDumpAllAsync},

	{"TestSetResponseBodyTransformer", _test.TestSetResponseBodyTransformer},

	{"TestSetResultStateCheckFunc", _test.TestSetResultStateCheckFunc},

	{"TestCloneCookieJar", _test.TestCloneCookieJar},

	{"TestPeekDrain", _test.TestPeekDrain},

	{"TestLogger", _test.TestLogger},

	{"TestLoggerFromStandardLogger", _test.TestLoggerFromStandardLogger},

	{"TestTrailer", _test.TestTrailer},

	{"TestMustSendMethods", _test.TestMustSendMethods},

	{"TestSendMethods", _test.TestSendMethods},

	{"TestEnableDump", _test.TestEnableDump},

	{"TestEnableDumpTo", _test.TestEnableDumpTo},

	{"TestEnableDumpToFIle", _test.TestEnableDumpToFIle},

	{"TestBadRequest", _test.TestBadRequest},

	{"TestSetBodyMarshal", _test.TestSetBodyMarshal},

	{"TestDoAPIStyle", _test.TestDoAPIStyle},

	{"TestSetSuccessResult", _test.TestSetSuccessResult},

	{"TestSetBody", _test.TestSetBody},

	{"TestCookie", _test.TestCookie},

	{"TestSetBasicAuth", _test.TestSetBasicAuth},

	{"TestSetBearerAuthToken", _test.TestSetBearerAuthToken},

	{"TestHeader", _test.TestHeader},

	{"TestSetHeaderNonCanonical", _test.TestSetHeaderNonCanonical},

	{"TestQueryParam", _test.TestQueryParam},

	{"TestPathParam", _test.TestPathParam},

	{"TestSuccess", _test.TestSuccess},

	{"TestError", _test.TestError},

	{"TestForm", _test.TestForm},

	{"TestHostHeaderOverride", _test.TestHostHeaderOverride},

	{"TestTraceInfo", _test.TestTraceInfo},

	{"TestTraceOnTimeout", _test.TestTraceOnTimeout},

	{"TestAutoDetectRequestContentType", _test.TestAutoDetectRequestContentType},

	{"TestSetFileUploadCheck", _test.TestSetFileUploadCheck},

	{"TestUploadMultipart", _test.TestUploadMultipart},

	{"TestFixPragmaCache", _test.TestFixPragmaCache},

	{"TestSetFileBytes", _test.TestSetFileBytes},

	{"TestSetFileReader", _test.TestSetFileReader},

	{"TestSetFileWithRetry", _test.TestSetFileWithRetry},

	{"TestSetFile", _test.TestSetFile},

	{"TestSetFiles", _test.TestSetFiles},

	{"TestUploadCallback", _test.TestUploadCallback},

	{"TestDownloadCallback", _test.TestDownloadCallback},

	{"TestRequestDisableAutoReadResponse", _test.TestRequestDisableAutoReadResponse},

	{"TestRestoreResponseBody", _test.TestRestoreResponseBody},

	{"TestRetryBackOff", _test.TestRetryBackOff},

	{"TestRetryInterval", _test.TestRetryInterval},

	{"TestRetryFixedInterval", _test.TestRetryFixedInterval},

	{"TestAddRetryHook", _test.TestAddRetryHook},

	{"TestRetryOverride", _test.TestRetryOverride},

	{"TestAddRetryCondition", _test.TestAddRetryCondition},

	{"TestRetryWithUnreplayableBody", _test.TestRetryWithUnreplayableBody},

	{"TestRetryWithSetResult", _test.TestRetryWithSetResult},

	{"TestRetryWithModify", _test.TestRetryWithModify},

	{"TestRetryFalse", _test.TestRetryFalse},

	{"TestRetryTurnedOffWhenRetryCountEqZero", _test.TestRetryTurnedOffWhenRetryCountEqZero},

}

var benchmarks = []testing.InternalBenchmark{

}

var fuzzTargets = []testing.InternalFuzzTarget{

}

var examples = []testing.InternalExample{

}

func init() {

	testdeps.ModulePath = "github.com/imroc/req/v3"
	testdeps.ImportPath = "github.com/imroc/req/v3"
}

func main() {
	m := testing.MainStart(testdeps.TestDeps{}, tests, benchmarks, fuzzTargets, examples)

	os.Exit(m.Run())

}

